import { Montserrat } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

// Thêm Montserrat font
const montserrat = Montserrat({
  variable: "--font-montserrat", 
  subsets: ["latin"], 
});

export const metadata = {
  title: "ReadHub",
  description: "Generated by Nhom11",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} antialiased`}
      >
        <Toaster />
        {children}
      </body>
    </html>
  );
}
